"""
Generate a local demo .env for the platform.

Creates a real RSA-2048 keypair for JWT signing and writes a .env pointing at
localhost Postgres/Redis. Refuses to overwrite an existing .env.

These keys are for LOCAL DEMO USE ONLY — never reuse them anywhere real.

Usage:
    python scripts/bootstrap_demo.py
"""

from __future__ import annotations

import sys
from pathlib import Path

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import rsa

ROOT = Path(__file__).resolve().parent.parent
ENV_PATH = ROOT / ".env"


def _indent_pem(pem: str) -> str:
    """Keep a multi-line PEM on one logical .env line via a quoted value."""
    return pem.strip()


def main() -> int:
    if ENV_PATH.exists():
        print(f"SKIP: {ENV_PATH} already exists; leaving it untouched.")
        return 0

    key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    private_pem = key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption(),
    ).decode()
    public_pem = key.public_key().public_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PublicFormat.SubjectPublicKeyInfo,
    ).decode()

    content = f"""# LOCAL DEMO ONLY — generated by scripts/bootstrap_demo.py
# Contains a throwaway RSA keypair. Never reuse these values.

APP_NAME="Repo SaaS (demo)"
ENVIRONMENT=development
DEBUG=true
LOG_LEVEL=INFO

DATABASE_URL=postgresql+asyncpg://reposaaas:reposaaas@localhost:5432/reposaaas
REDIS_URL=redis://localhost:6379/0

AWS_REGION=ap-south-1
S3_BUCKET_NAME=reposaaas-documents-dev

JWT_ALGORITHM=RS256
JWT_PRIVATE_KEY="{_indent_pem(private_pem)}"
JWT_PUBLIC_KEY="{_indent_pem(public_pem)}"
JWT_ACCESS_TOKEN_EXPIRE_SECONDS=3600

VERIFICATION_BASE_URL=http://localhost:3000
CORS_ALLOWED_ORIGINS=["http://localhost:3000"]
"""

    ENV_PATH.write_text(content, encoding="utf-8")
    print(f"OK: wrote {ENV_PATH}")
    print("Generated a fresh RSA-2048 keypair for JWT signing (demo only).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
